public enum TipoToken {
  // Palavras Reservadas
   ABSOLUTE, ARRAY, BEGIN, CASE, CHAR, CONST, DIV, DO, DOWTO ,ELSE, END ,EXTERNAL, FILE ,FOR, FORWARD, FUNC, FUNCTION, GOTO, IF, IMPLEMENTATION, INTEGER, INTERFACE, INTERRUPT, LABEL, MAIN, NIL, NIT, OF, PACKED, PROC, PROGRAM, REAL, RECORD, REPEAT, SET, SHL, SHR, STRING, THEN, TO, TYPE, UNIT, UNTIL, USES, VAR, WHILE, WITH, XOR,
    

    // Outros Tokens
    IDENTIFICADOR,
    NUMERO_INTEIRO, NUMERO_REAL,
    OPERADOR_ARITMETICO, OPERADOR_RELACIONAL, OPERADOR_LOGICO,
    ATRIBUICAO,
    SIMBOLO_ESPECIAL,
    FIM_DE_ARQUIVO
}
